# view-augur.ps1 â€” launch the live animated crawl over a MODEL-GENERATED store.
#
#   .\view-augur.ps1              # starts genserver.py (model is the backend, :3000) + UI (:7000) + browser
#   .\view-augur.ps1 -NoBackend   # UI only â€” point it at a site you're already running
#
# In the page, target = http://localhost:3000, hit Crawl. The model hallucinates each page as
# the crawler reaches it. Press Enter in this window to stop the servers.
param([switch]$NoBackend)

$ErrorActionPreference = "Stop"
Set-Location $PSScriptRoot

$backend = $null
if (-not $NoBackend) {
    Write-Host "Starting model-backed store (genserver.py) on :3000..." -ForegroundColor Cyan
    $backend = Start-Process python -ArgumentList "genserver.py" -PassThru -WindowStyle Hidden
}

Write-Host "Starting Augur UI on :7000..." -ForegroundColor Cyan
$srv = Start-Process python -ArgumentList "serve.py" -PassThru -WindowStyle Hidden
Start-Sleep -Seconds 1
Start-Process "http://localhost:7000"

Write-Host "`nAugur UI: http://localhost:7000   (the store is being generated by the model)" -ForegroundColor Green
Read-Host "Press Enter to stop the servers"

if ($srv)     { Stop-Process -Id $srv.Id     -Force -ErrorAction SilentlyContinue }
if ($backend) { Stop-Process -Id $backend.Id -Force -ErrorAction SilentlyContinue }
Write-Host "Stopped." -ForegroundColor Cyan
